title: FinanceMastery
description: "AI-powered blog to master personal finance, wealth, and financial freedom."
baseurl: ""            # leave empty for root
url: "https://FinanceMastery.github.io/FinanceMastery"
theme: minima
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
